<?php
namespace App\Http\Controllers; use App\Http\Resources\TicketResource; use App\Models\Membership; use App\Models\Ticket; use Illuminate\Http\JsonResponse; use Illuminate\Http\Request;
final class ApiTicketController extends Controller {
 private function membership(Request $r,int $org):Membership{$m=Membership::where(['user_id'=>$r->user()->id,'organization_id'=>$org,'status'=>'active'])->first();abort_unless($m,403,'You are not a member of this organization.');return $m;}
 public function index(Request $r):JsonResponse{$org=$r->integer('organization_id');$this->membership($r,$org);$items=$r->attributes->get('lab_empty')?collect():Ticket::where('organization_id',$org)->with('customer')->orderBy('id')->get();return response()->json(['data'=>TicketResource::collection($items)->resolve(),'meta'=>['count'=>$items->count()],'requestId'=>$r->attributes->get('request_id')]);}
 public function store(Request $r):JsonResponse{$org=$r->integer('organization_id');$m=$this->membership($r,$org);abort_if($m->role==='viewer',403,'Viewers cannot create tickets.');$d=$r->validate(['organization_id'=>['required','integer'],'customerId'=>['required','integer'],'subject'=>['required','string','min:5','max:120'],'priority'=>['required','in:low,normal,high,urgent']]);$customer=\App\Models\Customer::where('organization_id',$org)->find($d['customerId']);if(!$customer)return response()->json(['error'=>['type'=>'validation','message'=>'The representation is invalid.','fields'=>['customerId'=>['The customer must belong to this organization.']]],'request_id'=>$r->attributes->get('request_id')],422);$ticket=Ticket::create(['organization_id'=>$org,'customer_id'=>$customer->id,'subject'=>$d['subject'],'priority'=>$d['priority']])->load('customer');\Log::info('ticket.created',['request_id'=>$r->attributes->get('request_id'),'user_id'=>$r->user()->id,'organization_id'=>$org,'ticket_id'=>$ticket->id]);return response()->json(['data'=>(new TicketResource($ticket))->resolve(),'requestId'=>$r->attributes->get('request_id')],201,['Location'=>"/api/v1/tickets/{$ticket->id}"]);}
 public function show(Request $r,int $ticket):JsonResponse{$item=Ticket::findOrFail($ticket);$this->membership($r,$item->organization_id);return response()->json(['data'=>(new TicketResource($item->load('customer')))->resolve(),'requestId'=>$r->attributes->get('request_id')]);}
 public function destroy(Request $r,int $ticket):JsonResponse{$item=Ticket::findOrFail($ticket);$m=$this->membership($r,$item->organization_id);abort_unless(in_array($m->role,['owner','admin'],true),403);$item->delete();return response()->json([],204);}
}
