<?php
namespace App\Http\Controllers; use App\Http\Resources\TicketResource; use App\Models\Membership; use App\Models\Ticket; use Illuminate\Http\JsonResponse; use Illuminate\Http\Request;
final class ApiTicketController extends Controller {
 private function membership(Request $r,int $org):Membership{$m=Membership::where(['user_id'=>$r->user()->id,'organization_id'=>$org,'status'=>'active'])->first();abort_unless($m,403,'You are not a member of this organization.');return $m;}
 public function index(Request $r):JsonResponse{$org=$r->integer('organization_id');$this->membership($r,$org);$items=$r->attributes->get('lab_empty')?collect():Ticket::where('organization_id',$org)->with('customer')->orderBy('id')->get();return response()->json(['data'=>TicketResource::collection($items)->resolve(),'meta'=>['count'=>$items->count()],'requestId'=>$r->attributes->get('request_id')]);}
 public function store(Request $r):JsonResponse{$org=$r->integer('organization_id');$m=$this->membership($r,$org);abort_if($m->role==='viewer',403,'Viewers cannot create tickets.');$d=$r->validate(['organization_id'=>['required','integer'],'customerId'=>['required','integer'],'subject'=>['required','string','min:5','max:120'],'priority'=>['required','in:low,normal,high,urgent']]);$customer=\App\Models\Customer::where('organization_id',$org)->find($d['customerId']);if(!$customer)return response()->json(['error'=>['type'=>'validation','message'=>'The representation is invalid.','fields'=>['customerId'=>['The customer must belong to this organization.']]],'request_id'=>$r->attributes->get('request_id')],422);$key=$r->attributes->get('lab_profile')==='debug-capstone'?null:$r->header('Idempotency-Key');if($key!==null&&(!is_string($key)||!preg_match('/^[A-Za-z0-9._-]{8,100}$/',$key)))return response()->json(['error'=>['type'=>'validation','message'=>'Idempotency-Key must contain 8-100 safe characters.'],'request_id'=>$r->attributes->get('request_id')],422);$hash=hash('sha256',json_encode($d,JSON_THROW_ON_ERROR));$existing=$key===null?null:\App\Models\IdempotencyRequest::where(['organization_id'=>$org,'key'=>$key])->first();if($existing){if($existing->request_hash!==$hash)return response()->json(['error'=>['type'=>'conflict','message'=>'That idempotency key was already used for a different request.'],'request_id'=>$r->attributes->get('request_id')],409);return response()->json($existing->response,$existing->status,['Idempotency-Replayed'=>'true']);}$result=\DB::transaction(function()use($org,$customer,$d,$key,$hash,$r){$ticket=Ticket::create(['organization_id'=>$org,'customer_id'=>$customer->id,'subject'=>$d['subject'],'priority'=>$d['priority']])->load('customer');$jobId=(string)\Illuminate\Support\Str::uuid();$correlation=$r->attributes->get('request_id');$delivery=\App\Models\IntegrationDelivery::create(['organization_id'=>$org,'ticket_id'=>$ticket->id,'job_id'=>$jobId,'correlation_id'=>$correlation]);$body=['data'=>(new TicketResource($ticket))->resolve(),'requestId'=>$correlation,'jobId'=>$jobId];if($key!==null)\App\Models\IdempotencyRequest::create(['organization_id'=>$org,'key'=>$key,'request_hash'=>$hash,'ticket_id'=>$ticket->id,'response'=>$body,'status'=>201]);if($r->attributes->get('lab_profile')!=='debug-capstone')\App\Jobs\DeliverTicketNotification::dispatch($delivery->id,$jobId,$correlation);return [$ticket,$body];});[$ticket,$body]=$result;if(!$r->attributes->get('lab_stale_cache')&&$r->attributes->get('lab_profile')!=='debug-capstone')app(\App\Services\DashboardSummary::class)->forget($org);\Log::info('ticket.created',['user_id'=>$r->user()->id,'organization_id'=>$org,'ticket_id'=>$ticket->id,'job_id'=>$body['jobId'],'correlation_id'=>$r->attributes->get('request_id')]);return response()->json($body,201,['Location'=>"/api/v1/tickets/{$ticket->id}"]);}
 public function show(Request $r,int $ticket):JsonResponse{$item=Ticket::findOrFail($ticket);$this->membership($r,$item->organization_id);return response()->json(['data'=>(new TicketResource($item->load('customer')))->resolve(),'requestId'=>$r->attributes->get('request_id')]);}
 public function destroy(Request $r,int $ticket):JsonResponse{$item=Ticket::findOrFail($ticket);$m=$this->membership($r,$item->organization_id);abort_unless(in_array($m->role,['owner','admin'],true),403);$org=$item->organization_id;$item->delete();app(\App\Services\DashboardSummary::class)->forget($org);return response()->json([],204);}
}
