<?php
namespace Tests\Feature;
use App\Models\Customer; use App\Models\Ticket; use Illuminate\Foundation\Testing\RefreshDatabase; use Tests\TestCase;
final class PartFiveApiTest extends TestCase { use RefreshDatabase;
 public function test_authentication_and_contract_shape():void{[, $o]=$this->member();$this->getJson('/api/v1/tickets?organization_id='.$o->id)->assertStatus(401)->assertJsonPath('error.type','unauthenticated');[$u]=$this->member();$this->actingAs($u)->getJson('/api/v1/tickets?organization_id='.$u->memberships()->first()->organization_id)->assertOk()->assertJsonStructure(['data','meta'=>['count'],'requestId']);}
 public function test_create_serializes_camel_case_and_returns_201():void{[$u,$o]=$this->member();$c=Customer::create(['organization_id'=>$o->id,'name'=>'Northwind','email'=>'n@test.test']);$this->actingAs($u)->postJson('/api/v1/tickets',['organization_id'=>$o->id,'customerId'=>$c->id,'subject'=>'A useful subject','priority'=>'high'])->assertCreated()->assertJsonPath('data.customerId',$c->id)->assertJsonMissingPath('data.customer_id');$this->assertDatabaseHas('tickets',['organization_id'=>$o->id,'subject'=>'A useful subject']);}
 public function test_viewer_is_forbidden_and_other_tenant_is_isolated():void{[$viewer,$o]=$this->member('viewer');$c=Customer::create(['organization_id'=>$o->id,'name'=>'N','email'=>'n@test.test']);$this->actingAs($viewer)->postJson('/api/v1/tickets',['organization_id'=>$o->id,'customerId'=>$c->id,'subject'=>'Forbidden create','priority'=>'normal'])->assertForbidden();[$outsider]=$this->member();$ticket=Ticket::create(['organization_id'=>$o->id,'customer_id'=>$c->id,'subject'=>'Secret']);$this->actingAs($outsider)->getJson('/api/v1/tickets/'.$ticket->id)->assertForbidden();}
 public function test_lab_controls_are_off_unless_explicitly_enabled():void{[$u,$o]=$this->member();$this->actingAs($u)->withHeader('X-RelayDesk-Lab','empty')->getJson('/api/v1/tickets?organization_id='.$o->id)->assertOk()->assertJsonCount(0,'data');}
}
